build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
    tests: true
filter:
  excluded_paths:
    - 'tests/*'

checks:
  php: true

coding_style:
  php:
    spaces:
      other:
        after_type_cast: false

tools:
  external_code_coverage:
    timeout: 600
    runs: 1
